import html2pdf from 'html2pdf.js/dist/html2pdf.min.js';

export const exportDashboardToPdf = async () => {

  const fileName = `Daily_Traffic_Summary_${new Date().toISOString().split('T')[0]}.pdf`;

  try {

    const pdfContainer = document.createElement('div');

    pdfContainer.innerHTML = `
    <div style="font-family: Arial, sans-serif; background:#ffffff; padding:20px; width:210mm">

      <!-- HEADER -->
      <div style="margin-bottom:20px">
        <h2 style="margin:0">Smart Traffic Monitoring System</h2>
        <p style="color:#555">Daily Traffic Summary Report</p>
        <p style="font-size:12px">Date: ${new Date().toLocaleDateString()}</p>
        <hr/>
      </div>

      <!-- STAT CARDS -->
      <div style="display:grid; grid-template-columns: repeat(4, 1fr); gap:12px; margin-bottom:20px">

        <div style="border:1px solid #ddd; padding:12px; border-radius:8px">
          <p style="color:#555; font-size:12px">Total Vehicles Today</p>
          <h2 style="margin:5px 0">24,580</h2>
          <p style="color:green; font-size:12px">↑ 12% from yesterday</p>
        </div>

        <div style="border:1px solid #ddd; padding:12px; border-radius:8px">
          <p style="color:#555; font-size:12px">Active Cameras</p>
          <h2 style="margin:5px 0">48</h2>
        </div>

        <div style="border:1px solid #ddd; padding:12px; border-radius:8px">
          <p style="color:#555; font-size:12px">Congested Lanes</p>
          <h2 style="margin:5px 0">8</h2>
          <p style="color:red; font-size:12px">↓ 3% from yesterday</p>
        </div>

        <div style="border:1px solid #ddd; padding:12px; border-radius:8px">
          <p style="color:#555; font-size:12px">Emergency Events</p>
          <h2 style="margin:5px 0">3</h2>
        </div>

      </div>

      <!-- TRAFFIC DENSITY (MOCK GRAPH) -->
      <div style="border:1px solid #ddd; padding:15px; border-radius:8px; margin-bottom:20px">
        <h4 style="margin-bottom:10px">Traffic Density (Vehicles per hour)</h4>
        <img 
          src="https://dummyimage.com/800x300/e5f0ff/000000&text=Traffic+Density+Graph+(Mock)"
          style="width:100%; border-radius:6px"
        />
      </div>

      <!-- SIGNAL PERFORMANCE -->
      <div style="border:1px solid #ddd; padding:15px; border-radius:8px">
        <h4 style="margin-bottom:10px">Signal Performance (Efficiency %)</h4>

        <table style="width:100%; border-collapse:collapse">
          <tr>
            <th style="border:1px solid #ddd; padding:8px">Location</th>
            <th style="border:1px solid #ddd; padding:8px">Efficiency</th>
          </tr>
          <tr>
            <td style="border:1px solid #ddd; padding:8px">MG Road</td>
            <td style="border:1px solid #ddd; padding:8px">92%</td>
          </tr>
          <tr>
            <td style="border:1px solid #ddd; padding:8px">Whitefield</td>
            <td style="border:1px solid #ddd; padding:8px">88%</td>
          </tr>
          <tr>
            <td style="border:1px solid #ddd; padding:8px">Indiranagar</td>
            <td style="border:1px solid #ddd; padding:8px">75%</td>
          </tr>
        </table>

      </div>

      <!-- FOOTER -->
      <div style="margin-top:30px; text-align:center; font-size:12px; color:#777">
        Generated by Smart Traffic Monitoring System
      </div>

    </div>
    `;

    document.body.appendChild(pdfContainer);

    const options = {
      margin: 8,
      filename: fileName,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: {
        scale: 2,
        backgroundColor: '#ffffff',
        useCORS: true
      },
      jsPDF: {
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      }
    };

    await html2pdf().set(options).from(pdfContainer).save();

    pdfContainer.remove();

    return {
      fileName,
      fileType: 'PDF'
    };

  } catch (error) {

    console.error('PDF Export Error:', error);

    return {
      fileName,
      fileType: 'PDF'
    };
  }
};
